package dev.mikko.shirocheck;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * 由 tools/gen_rules.py 从两个一手源生成,请勿手工编辑。
 * 源 A:https://shiro.apache.org/security-reports.html(条目全集 + 描述原文 + 触发条件)
 * 源 B:GitHub Advisory API(受影响模块坐标 + 结构化版本区间 + 评级)
 *
 * <p>粒度是 <b>CVE × 模块</b>:同一编号在不同模块上的受影响区间可以不同。
 */
public final class CveTable {
    private CveTable() {}

    public static final String GENERATED_FROM = "shiro.apache.org/security-reports.html + GitHub Advisory API";

    /** 官方页面上的条目总数(用于报告里说明覆盖范围)。 */
    public static final int OFFICIAL_TOTAL = 26;

    private static final List<Cve> ALL = new ArrayList<>();

    static {
        add("CVE-2026-56091", "shiro-guice", "high", -1.0, "unreviewed", false, "GitHub advisory 仍是 unreviewed(尚未标注受影响包),而 Dependabot 只用 reviewed 的条目做告警", "", false, "3.0.0", false, "3.0.0", true, "GUICE", "仅当通过 shiro-guice 模块在 web servlet 环境下使用", "When using Apache Shiro with the shiro-guice module in a web servlet context, a specially crafted HTTP request may cause an authentication bypass.", "When using Apache Shiro with the shiro-guice module in a web servlet context, a specially crafted HTTP request may cause an authentication bypass. This vulnerability is similar to CVE-2020-1957 , except that it affects the shiro-guice module instead of the shiro-spring module. This issue affects all Apache Shiro versions through 2.x, and 3.0.0-alpha-1 only when using shiro-guice module in a web se", "shiro.apache.org 官方描述原文");
        add("CVE-2026-56130", "shiro-web", "low", -1.0, "unreviewed", false, "GitHub advisory 仍是 unreviewed(尚未标注受影响包),而 Dependabot 只用 reviewed 的条目做告警", "1.2.4", true, "3.0.0", false, "3.0.0", true, "REMEMBERME", "仅当启用了 RememberMe 功能", "\"Remember me\" cookie age is not verified on the server.", "\"Remember me\" cookie age is not verified on the server. This potentially allows an attacker to intercept a valid cookie and reuse it indefinitely, even after the configured expiration time has passed. This issue affects all Apache Shiro versions from 1.2.4 through 2.x, and 3.0.0-alpha-1, only when RememberMe functionality is enabled. Mitigation: Upgrade to version 3.0.0 or later, which fixes the i", "shiro.apache.org 官方描述原文");
        add("CVE-2026-49268", "shiro-core", "high", -1.0, "reviewed", true, "", "", false, "2.2.1", false, "2.2.1", true, "LDAP", "仅当使用 DefaultLdapRealm(用户名未转义即拼进 LDAP DN)", "Apache Shiro: LDAP DN Injection in DefaultLdapRealm", "A remote attacker can inject LDAP special characters into the Distinguished Name (DN) construction in DefaultLdapRealm class. User-supplied username input is directly concatenated into the LDAP DN template without any escaping of RFC 2253 special characters. This allows an attacker to manipulate the DN structure used for LDAP bind authentication, potentially bypassing authentication or impersonati", "GitHub Advisory API");
        add("CVE-2026-49268", "shiro-core", "high", -1.0, "reviewed", true, "", "3.0.0-alpha-0", true, "3.0.0-alpha-2", false, "3.0.0-alpha-2", false, "LDAP", "仅当使用 DefaultLdapRealm(用户名未转义即拼进 LDAP DN)", "Apache Shiro: LDAP DN Injection in DefaultLdapRealm", "A remote attacker can inject LDAP special characters into the Distinguished Name (DN) construction in DefaultLdapRealm class. User-supplied username input is directly concatenated into the LDAP DN template without any escaping of RFC 2253 special characters. This allows an attacker to manipulate the DN structure used for LDAP bind authentication, potentially bypassing authentication or impersonati", "GitHub Advisory API");
        add("CVE-2026-48589", "shiro-jakarta-ee", "low", 5.4, "reviewed", true, "", "2.0-alpha", true, "2.2.1", false, "2.2.1", true, "JAKARTA", "仅当使用 shiro-jakarta-ee 集成模块", "Apache Shiro’s Jakarta EE module used the HTTP Referer header in certain cases to issue redirect after a user login", "Apache Shiro’s Jakarta EE module used the HTTP Referer header in certain cases to issue redirect after a user login. In affected versions, insufficient validation of this client-controlled value could allow an attacker to influence the redirect target in applications using the Jakarta EE module. This issue affects Apache Shiro from 2.0-alpha to 2.2.0, and 3.0.0-alpha-1, only when using shiro-jakar", "GitHub Advisory API");
        add("CVE-2026-48589", "shiro-jakarta-ee", "low", 5.4, "reviewed", true, "", "3.0.0-alpha-0", true, "3.0.0-alpha-2", false, "3.0.0-alpha-2", false, "JAKARTA", "仅当使用 shiro-jakarta-ee 集成模块", "Apache Shiro’s Jakarta EE module used the HTTP Referer header in certain cases to issue redirect after a user login", "Apache Shiro’s Jakarta EE module used the HTTP Referer header in certain cases to issue redirect after a user login. In affected versions, insufficient validation of this client-controlled value could allow an attacker to influence the redirect target in applications using the Jakarta EE module. This issue affects Apache Shiro from 2.0-alpha to 2.2.0, and 3.0.0-alpha-1, only when using shiro-jakar", "GitHub Advisory API");
        add("CVE-2026-44598", "shiro-jakarta-ee", "medium", -1.0, "reviewed", true, "", "2.0.0-alpha-0", true, "2.2.0", false, "2.2.0", true, "JAKARTA", "仅当使用 shiro-jakarta-ee 集成模块,且攻击者已有合法登录凭据", "Apache Shiro Vulnerable to Open Redirect, Server-Side Request Forgery", "With valid login credentials, URL Redirection to Untrusted Site ('Open Redirect'), Server-Side Request Forgery (SSRF) vulnerability in Apache Shiro. After successful login, Jakarta EE integration module uses shiroSavedRequest cookie to redirect to a particular web page after login. This cookie was not validated, and can be forged to send an HTTP GET request from the server itself to an arbitrary U", "GitHub Advisory API");
        add("CVE-2026-44598", "shiro-jakarta-ee", "medium", -1.0, "reviewed", true, "", "3.0.0-alpha-1", true, "3.0.0-alpha-1", true, "3.0.0-alpha-2", false, "JAKARTA", "仅当使用 shiro-jakarta-ee 集成模块,且攻击者已有合法登录凭据", "Apache Shiro Vulnerable to Open Redirect, Server-Side Request Forgery", "With valid login credentials, URL Redirection to Untrusted Site ('Open Redirect'), Server-Side Request Forgery (SSRF) vulnerability in Apache Shiro. After successful login, Jakarta EE integration module uses shiroSavedRequest cookie to redirect to a particular web page after login. This cookie was not validated, and can be forged to send an HTTP GET request from the server itself to an arbitrary U", "GitHub Advisory API");
        add("CVE-2026-43827", "shiro-core", "medium", -1.0, "reviewed", true, "", "1.0.0-incubating", true, "2.2.0", false, "2.2.0", true, "DEFAULT", "默认配置即受影响(登录成功后未换新 session id)", "Apache Shiro has a session fixation vulnerability", "Default configurations of Apache Shiro have a session fixation vulnerability. This issue affects Apache Shiro from 1.0 to 2.1.0, and 3.0.0-alpha-1. In the affected versions, when a session already exists, it is not invalidated upon successful login, nor is a new session being generated with a new ID. Mitigation: Upgrade to version 2.2.0, 3.0.0-alpha-2 or later, which fixes the issue by invalidatin", "GitHub Advisory API");
        add("CVE-2026-43827", "shiro-core", "medium", -1.0, "reviewed", true, "", "3.0.0-alpha-1", true, "3.0.0-alpha-1", true, "3.0.0-alpha-2", false, "DEFAULT", "默认配置即受影响(登录成功后未换新 session id)", "Apache Shiro has a session fixation vulnerability", "Default configurations of Apache Shiro have a session fixation vulnerability. This issue affects Apache Shiro from 1.0 to 2.1.0, and 3.0.0-alpha-1. In the affected versions, when a session already exists, it is not invalidated upon successful login, nor is a new session being generated with a new ID. Mitigation: Upgrade to version 2.2.0, 3.0.0-alpha-2 or later, which fixes the issue by invalidatin", "GitHub Advisory API");
        add("CVE-2026-43828", "shiro-web", "medium", -1.0, "reviewed", true, "", "1.0.0-incubating", true, "2.2.0", false, "2.2.0", true, "DEFAULT", "默认配置即受影响(Shiro 原生 session 管理器与 RememberMe 下发的 cookie 没有 Secure 属性)", "Apache Shiro sends sensitive cookies in HTTPS session without 'Secure' attribute", "Default configurations of Apache Shiro send sensitive cookies in HTTPS session without 'Secure' attribute. This issue affects Apache Shiro from 1.0 to 2.1.0, and 3.0.0-alpha-1. In the affected versions, Shiro-native session manager, as well as Remember-Me manager sends JSESSIONID and rememberMe cookies without secure attribute by default. Mitigation: Upgrade to version 2.2.0, 3.0.0-alpha-2 or late", "GitHub Advisory API");
        add("CVE-2026-43828", "shiro-web", "medium", -1.0, "reviewed", true, "", "3.0.0-alpha-1", true, "3.0.0-alpha-1", true, "3.0.0-alpha-2", false, "DEFAULT", "默认配置即受影响(Shiro 原生 session 管理器与 RememberMe 下发的 cookie 没有 Secure 属性)", "Apache Shiro sends sensitive cookies in HTTPS session without 'Secure' attribute", "Default configurations of Apache Shiro send sensitive cookies in HTTPS session without 'Secure' attribute. This issue affects Apache Shiro from 1.0 to 2.1.0, and 3.0.0-alpha-1. In the affected versions, Shiro-native session manager, as well as Remember-Me manager sends JSESSIONID and rememberMe cookies without secure attribute by default. Mitigation: Upgrade to version 2.2.0, 3.0.0-alpha-2 or late", "GitHub Advisory API");
        add("CVE-2026-23903", "shiro-spring", "medium", 5.3, "reviewed", true, "", "", false, "2.0.6", true, "2.1.0", true, "FILESYSTEM", "仅当静态文件放在大小写不敏感的文件系统上(如 macOS 默认设置),且 Shiro 里只配了小写的 filter 路径;只影响静态文件", "Apache Shiro has an Authentication Bypass", "If static files are served from a case-insensitive filesystem, such as default macOS setup, static files may be accessed by varying the case of the filename in the request. If only lower-case (common default) filters are present in Shiro, they may be bypassed this way. The issue only affects static files. Shiro 2.1.0 and later has a new parameters to remediate this issue shiro.ini: filterChainReso", "GitHub Advisory API");
        add("CVE-2026-23901", "shiro-core", "low", -1.0, "reviewed", true, "", "", false, "2.1.0", false, "2.1.0", true, "TIMING", "仅当攻击者能精确测量请求耗时;官方注明最可能的攻击面是本地攻击", "Apache Shiro Affected by an Observable Timing Discrepancy Vulnerability", "Prior to Shiro 2.1.0, code paths for non-existent vs. existing users are different enough, that a brute-force attack may be able to tell, by timing the requests only, determine if the request failed because of a non-existent user vs. wrong password. The most likely attack vector is a local attack only. Mitigation: Upgrade to version 2.1.0 or later, which fixes the issue, or ensure that the infrast", "GitHub Advisory API");
        add("CVE-2023-46749", "shiro-core", "medium", 6.5, "reviewed", true, "", "", false, "1.13.0", false, "1.13.0", true, "REWRITE", "仅当与 path rewriting 一起使用,且 blockSemicolon 被关掉(该开关默认是开的)", "Apache Shiro vulnerable to path traversal", "Apache Shiro before 1.13.0 or 2.0.0-alpha-4, may be susceptible to a path traversal attack that results in an authentication bypass when used together with path rewriting Mitigation: Update to Apache Shiro 1.13.0+ or 2.0.0-alpha-4+, or ensure blockSemicolon is enabled (this is the default).", "GitHub Advisory API");
        add("CVE-2023-46749", "shiro-core", "medium", 6.5, "reviewed", true, "", "2.0.0alpha1", true, "2.0.0alpha4", false, "2.0.0-alpha-4", true, "REWRITE", "仅当与 path rewriting 一起使用,且 blockSemicolon 被关掉(该开关默认是开的)", "Apache Shiro vulnerable to path traversal", "Apache Shiro before 1.13.0 or 2.0.0-alpha-4, may be susceptible to a path traversal attack that results in an authentication bypass when used together with path rewriting Mitigation: Update to Apache Shiro 1.13.0+ or 2.0.0-alpha-4+, or ensure blockSemicolon is enabled (this is the default).", "GitHub Advisory API");
        add("CVE-2023-46750", "shiro-web", "medium", 6.1, "reviewed", true, "", "", false, "1.13.0", false, "1.13.0", true, "FORMAUTH", "仅当使用 form 认证", "Open redirect in Apache Shiro", "URL Redirection to Untrusted Site ('Open Redirect') vulnerability when \"form\" authentication is used in Apache Shiro. Mitigation: Update to Apache Shiro 1.13.0+ or 2.0.0-alpha-4+.", "GitHub Advisory API");
        add("CVE-2023-46750", "shiro-web", "medium", 6.1, "reviewed", true, "", "2.0.0-alpha-1", true, "2.0.0-alpha-4", false, "2.0.0-alpha-4", true, "FORMAUTH", "仅当使用 form 认证", "Open redirect in Apache Shiro", "URL Redirection to Untrusted Site ('Open Redirect') vulnerability when \"form\" authentication is used in Apache Shiro. Mitigation: Update to Apache Shiro 1.13.0+ or 2.0.0-alpha-4+.", "GitHub Advisory API");
        add("CVE-2023-34478", "shiro-web", "critical", 9.8, "reviewed", true, "", "", false, "1.12.0", false, "1.12.0", true, "NONNORMALIZED", "仅当与「按未规范化路径路由」的 API 或 web 框架一起使用", "Path Traversal in Apache Shiro", "Apache Shiro, before 1.12.0 or 2.0.0-alpha-3, may be susceptible to a path traversal attack that results in an authentication bypass when used together with APIs or other web frameworks that route requests based on non-normalized requests. Mitigation: Update to Apache Shiro 1.12.0+ or 2.0.0-alpha-3+. Credit: Apache Shiro would like to thank swifty tk for reporting this issue.", "GitHub Advisory API");
        add("CVE-2023-34478", "shiro-web", "critical", 9.8, "reviewed", true, "", "2.0.0-alpha-1", true, "2.0.0-alpha-3", false, "2.0.0-alpha-3", true, "NONNORMALIZED", "仅当与「按未规范化路径路由」的 API 或 web 框架一起使用", "Path Traversal in Apache Shiro", "Apache Shiro, before 1.12.0 or 2.0.0-alpha-3, may be susceptible to a path traversal attack that results in an authentication bypass when used together with APIs or other web frameworks that route requests based on non-normalized requests. Mitigation: Update to Apache Shiro 1.12.0+ or 2.0.0-alpha-3+. Credit: Apache Shiro would like to thank swifty tk for reporting this issue.", "GitHub Advisory API");
        add("CVE-2023-22602", "shiro-web", "high", 7.5, "reviewed", false, "advisory 只挂在 org.apache.shiro:shiro-root 上 —— 那是 packaging=pom 的父 POM,Maven Central 上没有对应的 jar,没有项目会依赖它,按坐标匹配对不上", "", false, "1.11.0", false, "1.11.0", true, "SPRINGBOOT", "仅当与 Spring Boot 2.6+ 一起使用,且未把 spring.mvc.pathmatch.matching-strategy 设回 ant_path_matcher(两边路径匹配方式不一致才成立)", "Apache Shiro Interpretation Conflict vulnerability", "When using Apache Shiro before 1.11.0 together with Spring Boot 2.6+, a specially crafted HTTP request may cause an authentication bypass. The authentication bypass occurs when Shiro and Spring Boot are using different pattern-matching techniques. Both Shiro and Spring Boot < 2.6 default to Ant style pattern matching. Mitigation: Update to Apache Shiro 1.11.0, or set the following Spring Boot conf", "shiro.apache.org 官方描述原文");
        add("CVE-2022-40664", "shiro-core", "critical", 9.8, "reviewed", true, "", "", false, "1.10.0", false, "1.10.0", true, "DISPATCH", "仅当通过 RequestDispatcher 做 forward 或 include", "Apache Shiro Authentication Bypass vulnerability", "Apache Shiro before 1.10.0, Authentication Bypass Vulnerability in Shiro when forwarding or including via RequestDispatcher.", "GitHub Advisory API");
        add("CVE-2022-32532", "shiro-core", "critical", 9.8, "reviewed", true, "", "", false, "1.9.1", false, "1.9.1", true, "REGEX", "仅当使用了 RegexRequestMatcher 且配置不当", "Improper Authorization in Apache Shiro", "Apache Shiro before 1.9.1, A RegexRequestMatcher can be misconfigured to be bypassed on some servlet containers. Applications using RegExPatternMatcher with . in the regular expression are possibly vulnerable to an authorization bypass.", "GitHub Advisory API");
        add("CVE-2021-41303", "shiro-core", "critical", 9.8, "reviewed", true, "", "", false, "1.8.0", false, "1.8.0", true, "SPRINGBOOT", "仅当在 Spring Boot 环境下按特定方式配置", "Apache Shiro vulnerable to a specially crafted HTTP request causing an authentication bypass", "Apache Shiro before 1.8.0, when using Apache Shiro with Spring Boot, a specially crafted HTTP request may cause an authentication bypass.", "GitHub Advisory API");
        add("CVE-2020-17523", "shiro-web", "critical", 9.8, "reviewed", true, "", "", false, "1.7.1", false, "1.7.1", true, "SPRING", "仅当与 Spring 集成(shiro-spring / spring-boot-starter)", "Authentication bypass in Apache Shiro", "Apache Shiro before 1.7.1, when using Apache Shiro with Spring, a specially crafted HTTP request may cause an authentication bypass.", "GitHub Advisory API");
        add("CVE-2020-17523", "shiro-spring", "critical", 9.8, "reviewed", true, "", "", false, "1.7.1", false, "1.7.1", true, "SPRING", "仅当与 Spring 集成(shiro-spring / spring-boot-starter)", "Authentication bypass in Apache Shiro", "Apache Shiro before 1.7.1, when using Apache Shiro with Spring, a specially crafted HTTP request may cause an authentication bypass.", "GitHub Advisory API");
        add("CVE-2020-17523", "shiro-spring-boot-starter", "critical", 9.8, "reviewed", true, "", "", false, "1.7.1", false, "1.7.1", true, "SPRING", "仅当与 Spring 集成(shiro-spring / spring-boot-starter)", "Authentication bypass in Apache Shiro", "Apache Shiro before 1.7.1, when using Apache Shiro with Spring, a specially crafted HTTP request may cause an authentication bypass.", "GitHub Advisory API");
        add("CVE-2020-17510", "shiro-spring", "critical", 9.8, "reviewed", true, "", "", false, "1.7.0", false, "1.7.0", true, "SPRING", "仅当与 Spring 集成(shiro-spring)", "Authentication bypass in Apache Shiro", "Apache Shiro before 1.7.0, when using Apache Shiro with Spring, a specially crafted HTTP request may cause an authentication bypass. If you are NOT using Shiro’s Spring Boot Starter ( shiro-spring-boot-web-starter ), you must configure add the ShiroRequestMappingConfig autoconfiguration to your application or configure the equivalent manually .", "GitHub Advisory API");
        add("CVE-2020-13933", "shiro-core", "high", 7.5, "reviewed", true, "", "", false, "1.6.0", false, "1.6.0", true, "DEFAULT", "默认配置即受影响(特制请求可绕过 filter 链)", "Authentication bypass in Apache Shiro", "Apache Shiro before 1.6.0, when using Apache Shiro, a specially crafted HTTP request may cause an authentication bypass.", "GitHub Advisory API");
        add("CVE-2020-11989", "shiro-core", "critical", 9.8, "reviewed", true, "", "", false, "1.5.3", false, "1.5.3", true, "DEFAULT", "默认配置即受影响(特制请求可绕过 filter 链)", "Improper Authentication in Apache Shiro", "Apache Shiro before 1.5.3, when using Apache Shiro with Spring dynamic controllers, a specially crafted request may cause an authentication bypass.", "GitHub Advisory API");
        add("CVE-2020-1957", "shiro-core", "critical", 9.8, "reviewed", true, "", "", false, "1.5.2", false, "1.5.2", true, "SPRING", "仅当与 Spring 动态控制器一起使用", "Improper Authentication in Apache Shiro", "Apache Shiro before 1.5.2, when using Apache Shiro with Spring dynamic controllers, a specially crafted request may cause an authentication bypass.", "GitHub Advisory API");
        add("CVE-2019-12422", "shiro-core", "high", 7.5, "reviewed", true, "", "", false, "1.4.2", false, "1.4.2", true, "REMEMBERME", "仅当启用了 RememberMe(padding oracle 攻击 cookie 密文)", "Improper input validation in Apache Shiro", "Apache Shiro before 1.4.2, when using the default \"remember me\" configuration, cookies could be susceptible to a padding attack.", "GitHub Advisory API");
        add("CVE-2016-6802", "shiro-all", "high", 7.5, "reviewed", true, "", "", false, "1.3.2", false, "1.3.2", true, "CONTEXTPATH", "仅当应用部署在非根 context path 下", "Improper Access Control in Apache Shiro", "Apache Shiro before 1.3.2 allows attackers to bypass intended servlet filters and gain access by leveraging use of a non-root servlet context path.", "GitHub Advisory API");
        add("CVE-2016-6802", "shiro-web", "high", 7.5, "reviewed", true, "", "", false, "1.3.2", false, "1.3.2", true, "CONTEXTPATH", "仅当应用部署在非根 context path 下", "Improper Access Control in Apache Shiro", "Apache Shiro before 1.3.2 allows attackers to bypass intended servlet filters and gain access by leveraging use of a non-root servlet context path.", "GitHub Advisory API");
        add("CVE-2016-4437", "shiro-core", "critical", 9.8, "reviewed", true, "", "", false, "1.2.4", true, "1.2.5", true, "REMEMBERME", "仅当启用了 RememberMe 且仍在用默认的硬编码加密密钥", "Improper Access Control in Apache Shiro", "Apache Shiro before 1.2.5, when a cipher key has not been configured for the \"remember me\" feature, allows remote attackers to execute arbitrary code or bypass intended access restrictions via an unspecified request parameter.", "GitHub Advisory API");
        add("CVE-2014-0074", "shiro-core", "high", -1.0, "unreviewed", false, "GitHub advisory 仍是 unreviewed(尚未标注受影响包),而 Dependabot 只用 reviewed 的条目做告警", "", false, "1.2.3", false, "1.2.3", true, "LDAP", "仅当 LDAP 服务器开启了 unauthenticated bind(此时空用户名或空密码即可通过)", "Apache Shiro 1.x before 1.2.3, when using an LDAP server with unauthenticated bind enabled, allows remote attackers to bypass authentication via an empty (1)…", "Apache Shiro 1.x before 1.2.3, when using an LDAP server with unauthenticated bind enabled, allows remote attackers to bypass authentication via an empty (1) username or (2) password.", "shiro.apache.org 官方描述原文");
        add("CVE-2010-3863", "shiro-web", "medium", -1.0, "reviewed", false, "advisory 只挂在 org.apache.shiro:shiro-root 上 —— 那是 packaging=pom 的父 POM,Maven Central 上没有对应的 jar,没有项目会依赖它,按坐标匹配对不上", "", false, "1.1.0", false, "1.1.0", true, "DEFAULT", "默认配置即受影响(URI 路径未做规范化即与 shiro.ini 比对)", "Apache Shiro Path Traversal vulnerability", "Apache Shiro before 1.1.0, and JSecurity 0.9.x, does not canonicalize URI paths before comparing them to entries in the shiro.ini file, which allows remote attackers to bypass intended access restrictions via a crafted request, as demonstrated by the /./account/index.jsp URI. Donate to the ASF | License Copyright © 2008-2026 The Apache Software Foundation docReady( addPageEditLink() ); hljs.highli", "shiro.apache.org 官方描述原文");
    }

    private static void add(String id, String module, String ghSev, double ghScore,
                            String ghType, boolean alerts, String silentReason,
                            String low, boolean lowIncl, String high, boolean highIncl,
                            String fixedIn, boolean fixedAvailable,
                            String condKind, String condText,
                            String title, String desc, String rangeSource) {
        ALL.add(new Cve(id, module, ghSev, ghScore, ghType, alerts, silentReason,
                        low, lowIncl, high, highIncl, fixedIn, fixedAvailable,
                        condKind, condText, title, desc, rangeSource));
    }

    public static List<Cve> all() { return Collections.unmodifiableList(ALL); }
}
