package dev.mikko.shirocheck;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class ScannerTest {

    // ────────── 构造归档的小工具 ──────────

    private static byte[] zip(Map<String, byte[]> entries) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(bos)) {
            for (Map.Entry<String, byte[]> e : entries.entrySet()) {
                zos.putNextEntry(new ZipEntry(e.getKey()));
                zos.write(e.getValue());
                zos.closeEntry();
            }
        }
        return bos.toByteArray();
    }

    private static byte[] shiroJar(String artifact, String version) throws IOException {
        Map<String, byte[]> m = new LinkedHashMap<>();
        m.put("META-INF/maven/org.apache.shiro/" + artifact + "/pom.properties",
                ("version=" + version + "\ngroupId=org.apache.shiro\nartifactId=" + artifact + "\n")
                        .getBytes(StandardCharsets.UTF_8));
        m.put("org/apache/shiro/Dummy.class", new byte[]{1, 2, 3});
        return zip(m);
    }

    private static Path write(Path dir, String name, byte[] bytes) throws IOException {
        Path p = dir.resolve(name);
        Files.write(p, bytes);
        return p;
    }

    private static Optional<Scanner.Module> find(Scanner sc, String module) {
        return sc.modules().stream().filter(m -> m.module().equals(module)).findFirst();
    }

    // ────────── 测试 ──────────

    @Test
    @DisplayName("普通 jar:从 pom.properties 读出坐标与版本")
    void plainJar(@TempDir Path dir) throws IOException {
        Scanner sc = new Scanner();
        sc.scan(write(dir, "shiro-core-1.13.0.jar", shiroJar("shiro-core", "1.13.0")));

        assertEquals(1, sc.modules().size());
        Scanner.Module m = sc.modules().get(0);
        assertEquals("shiro-core", m.module());
        assertEquals("1.13.0", m.version().toString());
        assertEquals("pom.properties", m.source());
        assertFalse(m.insideAll());
    }

    @Test
    @DisplayName("🔴 pom.properties 必须按 key 解析:实测同批 jar 里键序就不一样")
    void pomPropertiesKeyOrderVaries(@TempDir Path dir) throws IOException {
        // 1.7.0 那批前面还带一行注释,且 artifactId 在 version 前面
        byte[] jar = zip(Map.of(
                "META-INF/maven/org.apache.shiro/shiro-spring/pom.properties",
                ("#Generated by org.apache.felix.bundleplugin\n#Fri Oct 23 15:54:52 CEST 2020\n"
                        + "groupId=org.apache.shiro\nartifactId=shiro-spring\nversion=1.7.0\n")
                        .getBytes(StandardCharsets.UTF_8)));
        Scanner sc = new Scanner();
        sc.scan(write(dir, "shiro-spring-1.7.0.jar", jar));

        assertEquals("shiro-spring", sc.modules().get(0).module());
        assertEquals("1.7.0", sc.modules().get(0).version().toString());
    }

    @Test
    @DisplayName("⭐ uber jar:自身与内含模块都要记,内含的标记 insideAll")
    void uberJarExposesBundledModules(@TempDir Path dir) throws IOException {
        Map<String, byte[]> m = new LinkedHashMap<>();
        for (String a : List.of("shiro-all", "shiro-core", "shiro-web", "shiro-spring")) {
            m.put("META-INF/maven/org.apache.shiro/" + a + "/pom.properties",
                    ("version=1.3.2\ngroupId=org.apache.shiro\nartifactId=" + a + "\n")
                            .getBytes(StandardCharsets.UTF_8));
        }
        Scanner sc = new Scanner();
        sc.scan(write(dir, "shiro-all-1.3.2.jar", zip(m)));

        assertEquals(4, sc.modules().size());
        assertFalse(find(sc, "shiro-all").orElseThrow().insideAll(), "uber jar 自身不算内含");
        assertTrue(find(sc, "shiro-core").orElseThrow().insideAll());
        assertTrue(find(sc, "shiro-spring").orElseThrow().insideAll(),
                "shiro-spring 的 CVE 必须能因为它被打进 uber jar 而判出来");
    }

    @Test
    @DisplayName("Spring Boot fat jar:展开 BOOT-INF/lib/ 里的模块")
    void fatJar(@TempDir Path dir) throws IOException {
        byte[] fat = zip(Map.of(
                "BOOT-INF/lib/shiro-core-1.13.0.jar", shiroJar("shiro-core", "1.13.0"),
                "BOOT-INF/lib/shiro-web-1.13.0.jar", shiroJar("shiro-web", "1.13.0"),
                "BOOT-INF/lib/unrelated-1.0.jar", zip(Map.of("a/B.class", new byte[]{1}))));
        Scanner sc = new Scanner();
        sc.scan(write(dir, "app.jar", fat));

        assertEquals(2, sc.modules().size());
        assertTrue(find(sc, "shiro-core").orElseThrow().path().contains("!/"),
                "fat jar 内的路径要能看出层级");
    }

    @Test
    @DisplayName("传统 WAR:展开 WEB-INF/lib/")
    void warFile(@TempDir Path dir) throws IOException {
        byte[] war = zip(Map.of("WEB-INF/lib/shiro-web-1.10.0.jar", shiroJar("shiro-web", "1.10.0")));
        Scanner sc = new Scanner();
        sc.scan(write(dir, "legacy.war", war));

        assertEquals("shiro-web", sc.modules().get(0).module());
        assertEquals("1.10.0", sc.modules().get(0).version().toString());
    }

    @Test
    @DisplayName("🔴 反斜杠路径的归档也要扫得出 —— 「没扫到」看起来和「你很安全」一模一样")
    void backslashEntryNames(@TempDir Path dir) throws IOException {
        byte[] war = zip(Map.of("WEB-INF\\lib\\shiro-core-1.9.0.jar", shiroJar("shiro-core", "1.9.0")));
        Scanner sc = new Scanner();
        sc.scan(write(dir, "weird.war", war));

        assertEquals(1, sc.modules().size(), "反斜杠归档一条都扫不出是最危险的失败");
        assertEquals("shiro-core", sc.modules().get(0).module());
    }

    @Test
    @DisplayName("jar 被改名时,pom.properties 说了算,文件名不算")
    void renamedJarStillIdentified(@TempDir Path dir) throws IOException {
        Scanner sc = new Scanner();
        sc.scan(write(dir, "mystery-lib.jar", shiroJar("shiro-core", "1.4.0")));

        assertEquals("shiro-core", sc.modules().get(0).module());
        assertEquals("1.4.0", sc.modules().get(0).version().toString());
    }

    @Test
    @DisplayName("没有 pom.properties 时退回 MANIFEST,再退回文件名")
    void fallsBackToManifestThenFileName(@TempDir Path dir) throws IOException {
        byte[] withMf = zip(Map.of("META-INF/MANIFEST.MF",
                "Manifest-Version: 1.0\r\nImplementation-Version: 1.5.3\r\n\r\n"
                        .getBytes(StandardCharsets.UTF_8)));
        Scanner a = new Scanner();
        a.scan(write(dir, "shiro-core-9.9.9.jar", withMf));
        assertEquals("1.5.3", a.modules().get(0).version().toString(), "MANIFEST 优先于文件名");
        assertEquals("MANIFEST", a.modules().get(0).source());

        Scanner b = new Scanner();
        b.scan(write(dir, "shiro-web-1.6.0.jar", zip(Map.of("x/Y.class", new byte[]{1}))));
        assertEquals("1.6.0", b.modules().get(0).version().toString());
        assertEquals("文件名", b.modules().get(0).source());
    }

    @Test
    @DisplayName("只认 org.apache.shiro —— 第三方同名构件不算")
    void ignoresOtherGroupIds(@TempDir Path dir) throws IOException {
        byte[] jar = zip(Map.of("META-INF/maven/com.example/shiro-core/pom.properties",
                "groupId=com.example\nartifactId=shiro-core\nversion=1.0.0\n"
                        .getBytes(StandardCharsets.UTF_8)));
        Scanner sc = new Scanner();
        sc.scan(write(dir, "fake.jar", jar));
        assertTrue(sc.modules().isEmpty());
    }

    @Test
    @DisplayName("🔴 版本号取不到时必须留下警告,不能静默丢掉")
    void unparseableVersionWarnsInsteadOfVanishing(@TempDir Path dir) throws IOException {
        byte[] jar = zip(Map.of("META-INF/maven/org.apache.shiro/shiro-core/pom.properties",
                "groupId=org.apache.shiro\nartifactId=shiro-core\nversion=RELEASE\n"
                        .getBytes(StandardCharsets.UTF_8)));
        Scanner sc = new Scanner();
        sc.scan(write(dir, "shiro-core-RELEASE.jar", jar));

        assertTrue(sc.modules().isEmpty());
        assertTrue(sc.warnings().stream().anyMatch(w -> w.contains("shiro-core")),
                "取不到版本必须说出来,否则用户会把它读成「你很安全」");
    }

    @Test
    @DisplayName("目录扫描 + 同一模块多版本都要留下(混合部署)")
    void directoryScanKeepsAllVersions(@TempDir Path dir) throws IOException {
        write(dir, "shiro-core-1.2.0.jar", shiroJar("shiro-core", "1.2.0"));
        write(dir, "shiro-core-2.0.0.jar", shiroJar("shiro-core", "2.0.0"));
        Scanner sc = new Scanner();
        sc.scan(dir);

        assertEquals(2, sc.modules().size(), "两个版本都要留,只取一个会漏判");
    }

    @Test
    @DisplayName("路径不存在时给警告而不是崩")
    void missingPathWarns(@TempDir Path dir) throws IOException {
        Scanner sc = new Scanner();
        sc.scan(dir.resolve("nope.jar"));
        assertTrue(sc.warnings().stream().anyMatch(w -> w.contains("路径不存在")));
    }
}
